# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenML Server
theme:
  name: material

nav:
  - Getting Started: installation.md
  - Contributing: CONTRIBUTING.md
  - Migration: migration.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
