# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: OpenML Server
theme:
  name: material

nav:
  - Getting Started: README.md
  - Contributing: CONTRIBUTING.md
