[project]
name = "openml-server-api"
version = "0.0.1"
authors = [
  { name="Pieter Gijsbers" },
]
description = "The Python-based REST API for OpenML."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "fastapi",
    "sqlalchemy",
    "uvicorn",
]

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[project.urls]
"Homepage" = "https://github.com/openml/server-api"
"Bug Tracker" = "https://github.com/openml/server-api/issues"

[tool.ruff]
select = ["A", "ARG", "B", "COM", "C4", "E", "EM", "F", "I001", "PT", "PTH", "T20", "RET", "SIM"]

[tool.mypy]
strict = true
plugins = [
    "pydantic.mypy"
]
