[project]
name = "OpenML Server API"
version = "0.0.1"
authors = [
  { name="Pieter Gijsbers", email="" },
]
description = "The Python-based REST API for OpenML."
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = []

[project.optional-dependencies]
dev = [
    "pre-commit",
]

[project.urls]
"Homepage" = "https://github.com/openml/server-api"
"Bug Tracker" = "https://github.com/openml/server-api/issues"

[tool.ruff]
select = ["B", "E", "F"]
